import Joi from 'joi';


export const createPropertySchema = Joi.object({
  category: Joi.string().required(),
  title: Joi.string().required().min(3).max(100),
  description: Joi.string().required().min(10).max(2000),
  neighborhood:Joi.string().optional(),
  features: Joi.array().items(Joi.string()),
   amenities: Joi.array().items(Joi.string()),
  distance_between_facility: Joi.array()
    .items(Joi.object().pattern(Joi.string(), Joi.number().min(0)))
    .default([]),
  property_location: Joi.string().optional(),
  property_type: Joi.string().required(),
  listing_type: Joi.string().required(),
  property_status: Joi.string().required(),
  furnishing: Joi.string().allow(null, ''),
  facing_direction: Joi.string().allow(null, ''),
  construction_status: Joi.string().allow(null, ''),
  possession_status: Joi.string().allow(null, ''),
  transaction_type: Joi.string().allow(null, ''),
  ownership_type: Joi.string().allow(null, ''),
  youTube_link: Joi.string().uri().allow(null, ''),
  longitude: Joi.string().allow(null, ''),
  latitude: Joi.string().allow(null, ''),
  country: Joi.string().allow(null, ''),
  region: Joi.string().allow(null, ''),
  city: Joi.string().allow(null, ''),
  number_of_bedrooms: Joi.number().min(0),
  number_of_bathrooms: Joi.number().min(0),
  number_of_floors: Joi.number().min(0),
  square: Joi.number().min(0),
  price: Joi.alternatives().try(Joi.number().min(0), Joi.string()),
  property_age: Joi.number().min(0),
  parking_spaces: Joi.number().min(0),
  total_floors: Joi.number().min(0),
  available_floor: Joi.number().min(0),
  street_width: Joi.number().min(0),
  plot_area: Joi.number().min(0),
  expected_pricing: Joi.number().min(0),
  price_per_sqft: Joi.number().min(0),
  booking_amount: Joi.number().min(0),
  maintenance_monthly: Joi.number().min(0),
  price_negotiable: Joi.boolean().default(false),
  available_from: Joi.date().allow(null),
});

export const buyAbilitySchema = Joi.object({
  monthly_income: Joi.number().required().min(0),
  monthly_expenses: Joi.number().required().min(0),
  down_payment: Joi.number().required().min(0),
  location: Joi.string().required(),
  property_type: Joi.string().required(),
  credit_score: Joi.number().min(300).max(850),
  employment_status: Joi.string().required().valid('employed', 'self-employed', 'business-owner'),
  employment_duration: Joi.number().min(0),
  other_loans: Joi.number().min(0),
  other_assets: Joi.number().min(0)
});

export const mortgageSchema = Joi.object({
  property_id: Joi.string().required(),
  loan_amount: Joi.number().required().min(0),
  down_payment: Joi.number().required().min(0),
  interest_rate: Joi.number().required().min(0),
  loan_term: Joi.number().required().min(1).max(30),
  monthly_income: Joi.number().required().min(0),
  employment_status: Joi.string().required().valid('employed', 'self-employed', 'business-owner'),
  employment_duration: Joi.number().required().min(0),
  credit_score: Joi.number().required().min(300).max(850),
  other_loans: Joi.number().min(0),
  other_assets: Joi.number().min(0),
  property_value: Joi.number().required().min(0),
  property_type: Joi.string().required(),
  property_use: Joi.string().required().valid('primary', 'secondary', 'investment'),
  property_location: Joi.string().required()
});

export const updatePropertySchema = Joi.object({
  category: Joi.string(),
  title: Joi.string().min(3).max(100),
  description: Joi.string().min(10).max(2000),
  features: Joi.array().items(Joi.string()),
  amenities: Joi.array().items(Joi.string()),
  property_location: Joi.string(),
  neighborhood:Joi.string().optional(),
  number_of_bedrooms: Joi.number().min(0),
  number_of_bathrooms: Joi.number().min(0),
  number_of_floors: Joi.number().min(0),
  square: Joi.number().min(0),
  price: Joi.number().min(0),
  property_type: Joi.string(),
  listing_type: Joi.string(),
  property_status: Joi.string(),
  property_age: Joi.number().min(0),
  furnishing: Joi.string(),
  parking_spaces: Joi.number().min(0),
  total_floors: Joi.number().min(0),
  available_floor: Joi.number().min(0),
  facing_direction: Joi.string(),
  street_width: Joi.number().min(0),
  plot_area: Joi.number().min(0),
  construction_status: Joi.string(),
  possession_status: Joi.string(),
  transaction_type: Joi.string(),
  ownership_type: Joi.string(),
  expected_pricing: Joi.number().min(0),
  price_per_sqft: Joi.number().min(0),
  booking_amount: Joi.number().min(0),
  maintenance_monthly: Joi.number().min(0),
  price_negotiable: Joi.boolean(),
  available_from: Joi.date(),
  longitude: Joi.string(),
  latitude: Joi.string(),
  country: Joi.string(),
  region: Joi.string(),
  city: Joi.string()
}); 