import Joi from 'joi';


export const createPropertySchema = Joi.object({
  category: Joi.string().required(),
  title: Joi.string().required().min(3).max(100),
  description: Joi.string().required().min(10).max(2000),
  neighborhood:Joi.string().optional(),
  features: Joi.array().items(Joi.string()),
   amenities: Joi.array().items(Joi.string()),
  distance_between_facility: Joi.array()
    .items(Joi.object().pattern(Joi.string(), Joi.number().min(0)))
    .default([]),
  property_location: Joi.string().optional(),
  property_type: Joi.string().required(),
  listing_type: Joi.string().required(),
  property_status: Joi.string().required(),
  furnishing: Joi.string().allow(null, ''),
  facing_direction: Joi.string().allow(null, ''),
  construction_status: Joi.string().allow(null, ''),
  possession_status: Joi.string().allow(null, ''),
  transaction_type: Joi.string().allow(null, ''),
  ownership_type: Joi.string().allow(null, ''),
  youTube_link: Joi.string().uri().allow(null, ''),
  longitude: Joi.string().allow(null, ''),
  latitude: Joi.string().allow(null, ''),
  country: Joi.string().allow(null, ''),
  region: Joi.string().allow(null, ''),
  city: Joi.string().allow(null, ''),
  number_of_bedrooms: Joi.number().min(0),
  number_of_bathrooms: Joi.number().min(0),
  number_of_floors: Joi.number().min(0),
  square: Joi.number().min(0),
  price: Joi.alternatives().try(Joi.number().min(0), Joi.string()),
  property_age: Joi.number().min(0),
  parking_spaces: Joi.number().min(0),
  total_floors: Joi.number().min(0),
  available_floor: Joi.number().min(0),
  street_width: Joi.number().min(0),
  plot_area: Joi.number().min(0),
  expected_pricing: Joi.number().min(0),
  price_per_sqft: Joi.number().min(0),
  booking_amount: Joi.number().min(0),
  maintenance_monthly: Joi.number().min(0),
  price_negotiable: Joi.boolean().default(false),
  available_from: Joi.date().allow(null),
});
